### ISSUE TITLE
iMessage2Spotify is not adding song to playlist when automation is run

### ISSUE THREAD

**Issue by wuke557** [iannotian/imessage2spotify-serverless#3]
I set up the shortcut and followed all the instructions. However when I receive a song in iMessage and the automation triggers + I run it, I do not see the song added to my playlist in Spotify. A imessage2spotify playlist was created in my library but it’s empty. Thanks for making this and for any help you can provide!

**Comment by iannotian** [comment]
Hey @wuke557, are you still seeing this issue?

**Comment by maggieees** [comment]
I am getting the same issue, how can i add the shortcut to the personal automation / what action should the automation have to get the spotify URL as the input in the shortcut?

**Comment by wuke557** [comment]
@iannotian Unfortunately yes still having this issue

**Comment by iannotian** [comment]
cc: @wuke557 

Thanks for your comment @maggieees. I observed someone trying to set it up, and you're on the money with that observation. I think it has to do with a change in default behavior for setting up shortcuts in iOS 16. It used to pipe in the message contents by default, but now the configuration must be manually set to look like this:

<p align="center" width="100%">
<img src="https://user-images.githubusercontent.com/1900909/210114264-907aed5b-cb64-4a8e-b78b-a2d90a66cd06.jpeg" width="250" />
</p>

Let me know if that works, and I'll update the documentation. Thanks for being patient! For some config reason, I don't get notifications on GH unless I'm tagged.

**Comment by maggieees** [comment]
This worked for me! Thank you!On Dec 30, 2022, at 1:57 PM, Ian MacFarlane ***@***.***> wrote:﻿
cc: @wuke557
Thanks for your comment @maggieees. I observed someone trying to set it up, and you're on the money with that observation. I think it has to do with a change in default behavior for setting up shortcuts in iOS 16. It used to pipe in the message contents by default, but now the configuration must be manually set to look like this:

Let me know if that works, and I'll update the documentation. Thanks for being patient! For some config reason, I don't get notifications on GH unless I'm tagged.

**Comment by iannotian** [comment]
@maggieees good to hear!

I'm going to close this. @wuke557 feel free to reopen if needed.

**Comment by wuke557** [comment]
Works for me as well, thank you!!
