### ISSUE TITLE
Is there a way to send songs to custom playlists?

### ISSUE THREAD

**Issue by mmarcouiller** [iannotian/imessage2spotify-serverless#7]
Im wondering if there is a variable or token I can update on my end to send to a different playlist than the one titled "iMessage2Spotify". Not sure if theres a way to do that in the shortcut app or if it would be something that would require alerting the source code and basically creating an entire new version of shortcut.

**Comment by iannotian** [comment]
Hi @mmarcouiller, apologies for the late response. Notifications don't seem to be working well on GH.

Yes, you can use a different playlist. There's a config file found at `Files.app > iCloud Drive > Shortcuts > imessage2spotify.json` which can be edited manually. Replace the existing value in "playlist_id" with your desired playlist's ID and iMessage2Spotify will place tracks in that playlist moving forward.

To get the playlist ID, you can look in the link generated by clicking on `Copy link to playlist`. For example, the ID for this link,

`https://open.spotify.com/playlist/asdf1234?si=0987780`

is `asdf1234`.
